### ISSUE TITLE
EffectEmitter::setSpeed not working

### ISSUE THREAD

**Issue by sp-rafael-lecina** [effekseer/EffekseerForCocos2d-x#12]
Hi ``EffeckEmitter::setSpeed`` is not working anymore on ``master``

I think this issue has something to do with this [line](https://github.com/effekseer/EffekseerForCocos2d-x/commit/b81f12156f62f30b27ce20a6a3221d7bd886ae82#diff-66bd9b56d2001539ba33db1ab1e860bfL19046) being removed when ``void InstanceGroup::Update( float deltaFrame, bool shown )`` was refactored on commit b81f12156f62f30b27ce20a6a3221d7bd886ae82
Also I feel it has to do with this [other ](https://github.com/effekseer/EffekseerForCocos2d-x/commit/b81f12156f62f30b27ce20a6a3221d7bd886ae82#diff-66bd9b56d2001539ba33db1ab1e860bfR16143) because instances doesn't receive ``deltaFrame`` scaled by the speed of the emitter

**Comment by durswd** [comment]
Thank you for your information. I will fix it

**Comment by durswd** [comment]
I fixed

**Comment by sp-rafael-lecina** [comment]
Thanks!
