### ISSUE TITLE
Crash when run effect

### ISSUE THREAD

**Issue by kienvn** [effekseer/EffekseerForCocos2d-x#21]
[Buff_Speed1.5.zip](https://github.com/effekseer/EffekseerForCocos2d-x/files/4466142/Buff_Speed1.5.zip)

**Comment by durswd** [comment]
I will check it

**Comment by durswd** [comment]
OK. I understand why it crashes. I will fix it.
please reduce sprites temporary

**Comment by durswd** [comment]
I fixed it on the master branch

**Comment by kienvn** [comment]
Thanks for your support
