### ISSUE TITLE
Issue with color multiplication in cocos version

### ISSUE THREAD

**Issue by dantonov** [effekseer/EffekseerForCocos2d-x#22]
Hello, I am using Effekseer for Cocos in game production for mobile phones. Version 1.52g.
The issue is that effect looks very different in Effekseer Editor and in a game. I've attached an archive with test effect and to screenshots from the editor and from a game:
[https://cloud.mail.ru/public/hvgv/5rZP3LAhX](url)

There are following files in archive:
COLOR_POWER_FX_152.png - screenshot from the editor
COLOR_POWER_FX_COCOS.png - screenshot from the game
t007_color_power_01.efk - the effect binary file
SHD_color_power_01_01.efkmat - generated shader for the effect
T_glow_01.png - texture
t007_color_power_01.efkefc - some other effect binary

As you can see on the screenshots the result is very different.
In shader I am multiplying color with some value that much greater that 1.0f, so the output gl_FragColor becomes something like vec4(5.0, 2.0, 1.0, 1.0) - normally it is white, but in the editor it's bright yellow.

The main question is how to achieve the same effect visuals in the game? Maybe you are using HDR while rendering in the editor by default?

**Comment by durswd** [comment]
Excuse me. Images are not found in this link.

using HDR - Yes

**Comment by dantonov** [comment]
Thank you for your fast reply, i was pretty sure it was HDR.
Try copy - paste link in a browser, i suppose i've marked prev link as internal githubs

https://cloud.mail.ru/public/2SL8/4DXqsQ9gj

**Comment by durswd** [comment]
Thank you. I will check in this weekend.

**Comment by durswd** [comment]
@dantonov 

COLOR_POWER_FX_152.png - screenshot from the editor
COLOR_POWER_FX_COCOS.png - screenshot from the game
t007_color_power_01.efkefc - some other effect binary

these files are not found in this file.
