### ISSUE TITLE
NANs while rendering trail

### ISSUE THREAD

**Issue by dantonov** [effekseer/EffekseerForCocos2d-x#23]

**Comment by dantonov** [comment]
Hello, i've found the following issue:
https://gyazo.com/ca73622fa65e9825c802a74d93b28c29

It could be fixed if you add zero-checks in function:
template<typename VERTEX>
void RenderSplines(const ::Effekseer_1_5::Mat44f& camera)

Like this:
if (!axis.IsZero())
	axis = axis.Normalize();

**Comment by durswd** [comment]
Thank you. I will fix in this weekend.

**Comment by durswd** [comment]
I fixed it on this branch.
https://github.com/effekseer/EffekseerForCocos2d-x/tree/15x_nan
