### ISSUE TITLE
Distortion not run on Android. Particle not run on IOS. 

### ISSUE THREAD

**Issue by linhdvzoro** [effekseer/EffekseerForCocos2d-x#26]
I'm using Cocos2dJS and not able to run some effect on some OS.
1. Distore not run on Android.
2. Particle not run on IOS.
My Effect: 
[effeckseer (2).zip](https://github.com/effekseer/EffekseerForCocos2d-x/files/5040386/effeckseer.2.zip)
Please help me check. Thanks you!

**Comment by durswd** [comment]
Please upload efkproj or efkefc and I can only checked with cocos2d-x because I don't know how to use Effekseer on cocod2-js

**Comment by durswd** [comment]
I succeeded in reproducing iOS bug. I try to fix it.

**Comment by durswd** [comment]
It seem that a texture whose size is not non power of two cannot be rendered.

**Comment by durswd** [comment]
I changed a texture size, the effect now can be shown.

**Comment by durswd** [comment]
I fixed about a distortion bug on the master branch

https://github.com/effekseer/EffekseerForCocos2d-x/commit/cc25795edb560ffa7292d760bfd89d004bad9bf5

**Comment by dangvanlinh** [comment]
> I changed a texture size, the effect now can be shown.
Can you show me detail how you change texture size? should i increase or decrease texture size? 
Thanks you very much for your support!

**Comment by dangvanlinh** [comment]
Thanks you very much for your support!

**Comment by linhdvzoro** [comment]
Thanks you very much for your support!
