### ISSUE TITLE
Difficult to update to the version 1.6x (v3)

### ISSUE THREAD

**Issue by IcarusLi** [effekseer/EffekseerForCocos2d-x#30]
createEffekSeerFiles_v3.py had deleted in this 1.6x version.
I can't update to 1.6 for my cocos2dx-v3 project,
There are a lot of files changed :(
19 files removed;40 files added;15 files rename; xxx files modified..  

I'm trying to read the source code, but it's too much. Is there any **outline** or something?

tks!

**Comment by durswd** [comment]
It is an overview. But it is old, so I need to update.
https://github.com/effekseer/Effekseer/blob/master/docs/Development/CodeOverview.md

I deleted createEffekseerFiles?v3.py because it is difficult to combine Effekseer into one file and build it without CMake
If you can compile cocos2dx-3 with Cmake, it is better to add Effekseer to cocos2d-x with Cmake

**Comment by IcarusLi** [comment]
I  made it !!!
![image](https://user-images.githubusercontent.com/18714890/127324681-435f6f52-a8d0-416f-945f-471fc3d6a775.png)

https://user-images.githubusercontent.com/18714890/127324705-02d7058d-503d-40b8-9873-faaf5ebac6e8.MP4

**Comment by IcarusLi** [comment]
Buiding with Visual Studio 2019, 

- v4/**3rdParty/stb_effekseer/stb_image_effekseer.h**  is missing. It can be found here [stb_image_effekseer.h](https://github.com/effekseer/Effekseer/blob/master/Dev/Cpp/3rdParty/stb_effekseer/stb_image_effekseer.h)

- v4/**Effekseer/Effekseer/Model/ModelLoader.cpp** and v4/**EffekseerRendererCommon/ModelLoader.cpp** produce outputs to the same location. [MSB8027](https://docs.microsoft.com/en-us/visualstudio/msbuild/errors/msb8027?view=vs-2019)

- v4/EffekseerForCocos2d-x/GL/Effekseer+GL.cpp 
![image](https://user-images.githubusercontent.com/18714890/127326414-f07d943b-1561-4a96-af8f-7ca0d71a6475.png)

- v4/EffekseerForCocos2d-x/EffekseerForCocos2d-x.h
add 
![image](https://user-images.githubusercontent.com/18714890/127326730-85cf5b00-4358-4554-b944-a4d1dc8797d5.png)
relpace as cocos2d::CustomCommand
 ![image](https://user-images.githubusercontent.com/18714890/127326822-0171d236-c849-4bb9-a67d-a1b7f8c62297.png)
 ![image](https://user-images.githubusercontent.com/18714890/127326836-707fb109-4e15-4168-9ac2-0ad58574ef60.png)

**Comment by durswd** [comment]
Cool!
