### ISSUE TITLE
Scheduler Update method order

### ISSUE THREAD

**Issue by chaochaodev** [effekseer/EffekseerForCocos2d-x#34]
Hello. 

In one frame, EffectEmitter Update method need to be called before EffectManager Update method. Otherwise, the Node property(position...) of the particle being rendered is last frame not current frame. 

I think the Update method order should be indicated in the help document.

The video below is an example. The red picture is the particle(by EffectEmitter). The green picture is a Sprite. Both call RunAction at the same time.

https://user-images.githubusercontent.com/24967892/147241035-88096ae4-0fb6-4bfd-9ae1-71176e77bd66.mov

**Comment by chaochaodev** [comment]
I am on the "15x" branch.

**Comment by durswd** [comment]
I wrote about it
