### ISSUE TITLE
Base Render Setting->Emissive Scaling not working in cocos

### ISSUE THREAD

**Issue by mayany** [effekseer/EffekseerForCocos2d-x#38]
Base Render Setting->Emissive Scaling value is not working in cocos 
such as Sample: Sample\00_Version16\Aura01_HDR.efkefc , in cocos the color not right

i'm using Effekseer162b version in windows

**Comment by durswd** [comment]
cocos2d-x doesn't support HDR
It need to edit cocos2d-x

**Comment by mayany** [comment]
ok thx
