### ISSUE TITLE
Effect only crash on Android

### ISSUE THREAD

**Issue by kienvn** [effekseer/EffekseerForCocos2d-x#6]
Effect not crash on win32, only crash on Android
[Bullet_01.zip](https://github.com/effekseer/EffekseerForCocos2d-x/files/2758366/Bullet_01.zip)

**Comment by kienvn** [comment]
![image](https://user-images.githubusercontent.com/3658115/51167680-c0047c00-18d9-11e9-97e3-76dcd4aedea8.png)

**Comment by durswd** [comment]
OK. I will check it.

**Comment by durswd** [comment]
I'm sorry for late. I start to check this problem

**Comment by durswd** [comment]
I fixed it.
https://github.com/effekseer/EffekseerForCocos2d-x/commit/48a26645633e93ed54c4953e51611629d03ea9fd

I'm going to release after few days.
If you need earlier, please download EffekseerForCocos2d-x from github
